services:
  manager:
    build:
      context: .
      dockerfile: Manager/Dockerfile
    container_name: crackhash-manager
    ports:
      - "8080:8080"
    environment:
      - Manager__RequestTimeoutSeconds=120
    depends_on:
      - worker1
      - worker2
      - worker3

  worker1:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    container_name: crackhash-worker1
    environment:
      - Worker__ManagerCallbackUrl=http://manager:8080/internal/api/manager/hash/crack/request

  worker2:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    container_name: crackhash-worker2
    environment:
      - Worker__ManagerCallbackUrl=http://manager:8080/internal/api/manager/hash/crack/request

  worker3:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    container_name: crackhash-worker3
    environment:
      - Worker__ManagerCallbackUrl=http://manager:8080/internal/api/manager/hash/crack/request

  worker4:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    container_name: crackhash-worker4
    environment:
      - Worker__ManagerCallbackUrl=http://manager:8080/internal/api/manager/hash/crack/request

